//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hitachiRework.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class siixsem_aoi_koh_youngEntities : DbContext
    {
        public siixsem_aoi_koh_youngEntities()
            : base("name=siixsem_aoi_koh_youngEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<isReworkable_Result> isReworkable(string serialPCB)
        {
            var serialPCBParameter = serialPCB != null ?
                new ObjectParameter("serialPCB", serialPCB) :
                new ObjectParameter("serialPCB", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<isReworkable_Result>("isReworkable", serialPCBParameter);
        }
    
        public virtual ObjectResult<getCmpListBySerial_Result> getCmpListBySerial(string serial)
        {
            var serialParameter = serial != null ?
                new ObjectParameter("serial", serial) :
                new ObjectParameter("serial", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getCmpListBySerial_Result>("getCmpListBySerial", serialParameter);
        }
    }
}
